export interface IDetalleResultadosMensual {
  Concepto: string,
  Numcta: string,
  Descr: string,
  SaldoMes: number,
  Real: number,
  Pspsto: number,
  Variacion: number,
  Pct: number,
  Ene: number,
  Feb: number,
  Mar: number,
  Abr: number,
  May: number,
  Jun: number,
  Jul: number,
  Ago: number,
  Sep: number,
  Oct: number,
  Nov: number,
  Dic: number,
  Suma: number
}
