export interface IDetalleResultadosMensual {
  IdEstadoResultadosI: number;
  titulo: string;
  numeroCuenta: string;
  saldoMonto: number;
  Concepto: string;
  Numcta: string;
  descripcion: string;
  Descr: string;
  SaldoMes: number;
  Real: number;
  Pspsto: number;
  Variacion: number;
  Pct: number;
  enero: number;
  febrero: number;
  marzo: number;
  abril: number;
  mayo: number;
  junio: number;
  julio: number;
  agosto: number;
  septiembre: number;
  octubre: number;
  noviembre: number;
  diciembre: number;
  totalAnual: number;
  Suma: number;
}
