export interface ISeries {
  Modelo: number,
  IdBI: number,
  Status: string,
  IdCliente: number,
  Nombre: string,
  RFC: string,
  Vendedor: string,
  Pedido: number,
  Fatcura: string,
  NumInventario: number,
  Serie: string,
  PrecioBase: number,
  Isan: number,
  PercIVA: number,
  ImporteTotal: number,
  CostoCompra: number,
  Incentivo: number,
  TotalCompra: number,
  Utilidad: number
}
